name: AAI
channels:
  - defaults
dependencies:
  - annotated-types=0.6.0=py311hca03da5_0
  - anyio=4.10.0=py311hca03da5_0
  - aom=3.6.0=h313beb8_0
  - appnope=0.1.4=py311hca03da5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py311h254cc4a_0
  - asttokens=3.0.0=py311hca03da5_0
  - async-lru=2.0.5=py311hca03da5_0
  - attrs=25.4.0=py311hca03da5_0
  - babel=2.16.0=py311hca03da5_0
  - beautifulsoup4=4.13.5=py311hca03da5_0
  - blas=1.0=openblas
  - bleach=6.2.0=py311hca03da5_0
  - bottleneck=1.4.2=py311hb9f6ed7_0
  - brotlicffi=1.0.9.2=py311h313beb8_1
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.9.9=hca03da5_0
  - cairo=1.18.4=h191e429_0
  - catalogue=2.0.10=py311hca03da5_0
  - certifi=2025.10.5=py311hca03da5_0
  - cffi=2.0.0=py311h3a083c1_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py311hca03da5_0
  - cloudpathlib=0.21.0=py311hca03da5_0
  - colorama=0.4.6=py311hca03da5_0
  - comm=0.2.1=py311hca03da5_0
  - confection=0.1.5=py311hd096484_0
  - contourpy=1.3.1=py311h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.11=py311h0962b89_0
  - cython-blis=1.0.1=py311h80987f9_0
  - dav1d=1.2.1=h80987f9_0
  - debugpy=1.8.16=py311h0962b89_0
  - decorator=5.2.1=py311hca03da5_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py311hca03da5_0
  - expat=2.7.1=h313beb8_0
  - fontconfig=2.15.0=h29935d0_0
  - fonttools=4.60.1=py311h254cc4a_0
  - freetype=2.13.3=h47d26ad_0
  - fribidi=1.0.10=h1a28f6b_0
  - gettext=0.21.0=hbdbcc25_2
  - graphite2=1.3.14=hc377ac9_1
  - h11=0.16.0=py311hca03da5_0
  - harfbuzz=10.2.0=he637ebf_1
  - httpcore=1.0.9=py311hca03da5_0
  - httpx=0.28.1=py311hca03da5_1
  - icu=73.1=h313beb8_0
  - idna=3.7=py311hca03da5_0
  - ipykernel=6.30.1=py311hca03da5_0
  - ipython=9.5.0=py311hca03da5_0
  - ipython_pygments_lexers=1.1.1=py311hca03da5_0
  - ipywidgets=8.1.5=py311hca03da5_0
  - jedi=0.19.2=py311hca03da5_0
  - jinja2=3.1.6=py311hca03da5_0
  - joblib=1.5.2=py311hca03da5_0
  - jpeg=9f=h2f69dba_0
  - json5=0.9.25=py311hca03da5_0
  - jsonschema=4.25.0=py311hca03da5_0
  - jsonschema-specifications=2023.7.1=py311hca03da5_0
  - jupyter=1.1.1=py311hca03da5_0
  - jupyter-lsp=2.2.5=py311hca03da5_0
  - jupyter_client=8.6.3=py311hca03da5_0
  - jupyter_console=6.6.3=py311hca03da5_0
  - jupyter_core=5.8.1=py311hca03da5_0
  - jupyter_events=0.12.0=py311hca03da5_0
  - jupyter_server=2.16.0=py311hca03da5_0
  - jupyter_server_terminals=0.5.3=py311hca03da5_0
  - jupyterlab=4.4.7=py311hca03da5_0
  - jupyterlab_pygments=0.3.0=py311hca03da5_0
  - jupyterlab_server=2.27.3=py311hca03da5_0
  - jupyterlab_widgets=3.0.15=py311hca03da5_0
  - kiwisolver=1.4.8=py311h313beb8_0
  - langcodes=3.5.0=py311hca03da5_0
  - language-data=1.3.0=py311hca03da5_0
  - lcms2=2.16=he26ebf3_1
  - lerc=4.0.0=h313beb8_0
  - libavif=1.1.1=h80987f9_0
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=h80987f9_0
  - libffi=3.4.4=hca03da5_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.84.4=h7a3292d_0
  - libiconv=1.16=h80987f9_3
  - libopenblas=0.3.30=hf2bb037_0
  - libopenjpeg=2.5.4=haa24f5a_0
  - libpng=1.6.50=h5c318fc_0
  - libsodium=1.0.20=h897f8a9_0
  - libtiff=4.7.0=h91aec0a_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxml2=2.13.8=h0b34f26_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=20.1.8=he822017_0
  - lz4-c=1.9.4=h313beb8_1
  - marisa-trie=1.3.1=py311h0962b89_0
  - markdown-it-py=4.0.0=py311hca03da5_0
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib=3.10.6=py311hca03da5_0
  - matplotlib-base=3.10.6=py311h066045a_0
  - matplotlib-inline=0.1.7=py311hca03da5_0
  - mdurl=0.1.2=py311hca03da5_0
  - mistune=3.1.2=py311hca03da5_0
  - murmurhash=1.0.12=py311h313beb8_0
  - nbclient=0.10.2=py311hca03da5_0
  - nbconvert=7.16.6=py311hca03da5_0
  - nbconvert-core=7.16.6=py311hca03da5_0
  - nbconvert-pandoc=7.16.6=py311hca03da5_0
  - nbformat=5.10.4=py311hca03da5_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=py311hca03da5_0
  - nltk=3.9.2=py311h661b90a_0
  - notebook=7.4.5=py311hca03da5_0
  - notebook-shim=0.2.4=py311hca03da5_0
  - numexpr=2.11.0=py311h8c72970_1
  - numpy=2.3.3=py311hc95ac1c_1
  - numpy-base=2.3.3=py311h8087a70_1
  - openjpeg=2.5.4=h959fc53_0
  - openssl=3.0.18=h9b4081a_0
  - overrides=7.4.0=py311hca03da5_0
  - packaging=25.0=py311hca03da5_1
  - pandas=2.3.3=py311hc6ded6b_0
  - pandoc=3.8=hca03da5_0
  - pandocfilters=1.5.1=py311hca03da5_0
  - parso=0.8.4=py311hca03da5_0
  - patsy=1.0.1=py311hca03da5_0
  - pcre2=10.46=h1dacb4a_0
  - pexpect=4.9.0=py311hca03da5_0
  - pillow=11.3.0=py311h6dd570d_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h09dc60e_0
  - platformdirs=4.3.7=py311hca03da5_0
  - preshed=3.0.9=py311h313beb8_0
  - prometheus_client=0.21.1=py311hca03da5_0
  - prompt-toolkit=3.0.52=py311hca03da5_0
  - prompt_toolkit=3.0.52=hd3eb1b0_0
  - psutil=7.0.0=py311h254cc4a_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.3=py311hca03da5_0
  - pycparser=2.23=py311hca03da5_0
  - pydantic=2.12.2=py311hca03da5_0
  - pydantic-core=2.41.4=py311h108b7f8_0
  - pygments=2.19.1=py311hca03da5_0
  - pyparsing=3.2.0=py311hca03da5_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0post0=py311hca03da5_2
  - python-fastjsonschema=2.20.0=py311hca03da5_0
  - python-json-logger=3.2.1=py311hca03da5_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py311hca03da5_0
  - pyyaml=6.0.2=py311h80987f9_0
  - pyzmq=27.1.0=py311h854a7ef_0
  - qtconsole=5.7.0=py311hca03da5_0
  - qtpy=2.4.3=py311hca03da5_0
  - readline=8.3=h0b18652_0
  - referencing=0.30.2=py311hca03da5_0
  - regex=2025.9.1=py311h254cc4a_0
  - requests=2.32.5=py311hca03da5_0
  - rfc3339-validator=0.1.4=py311hca03da5_0
  - rfc3986-validator=0.1.1=py311hca03da5_0
  - rich=13.9.4=py311hca03da5_0
  - rpds-py=0.22.3=py311h2aea54e_0
  - scikit-learn=1.7.2=py311hc6ded6b_0
  - seaborn=0.13.2=py311hca03da5_3
  - send2trash=1.8.2=py311hca03da5_1
  - setuptools=80.9.0=py311hca03da5_0
  - shellingham=1.5.0=py311hca03da5_0
  - six=1.17.0=py311hca03da5_0
  - smart_open=7.3.1=py311hca03da5_0
  - sniffio=1.3.0=py311hca03da5_0
  - soupsieve=2.5=py311hca03da5_0
  - spacy=3.8.2=py311h48ca7d4_0
  - spacy-legacy=3.0.12=py311hca03da5_0
  - spacy-loggers=1.0.4=py311hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - srsly=2.5.1=py311h313beb8_0
  - stack_data=0.6.3=py311hca03da5_0
  - statsmodels=0.14.5=py311h12bd487_0
  - terminado=0.18.1=py311hca03da5_0
  - thinc=8.3.2=py311h48ca7d4_1
  - threadpoolctl=3.5.0=py311hb6e6a13_0
  - tinycss2=1.4.0=py311hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - tornado=6.5.1=py311h80987f9_0
  - tqdm=4.67.1=py311hb6e6a13_0
  - traitlets=5.14.3=py311hca03da5_0
  - typer=0.9.0=py311hca03da5_0
  - typing-extensions=4.15.0=py311hca03da5_0
  - typing-inspection=0.4.2=py311hca03da5_0
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py311hca03da5_0
  - wasabi=1.1.3=py311hca03da5_0
  - wcwidth=0.2.13=py311hca03da5_0
  - weasel=0.4.1=py311hca03da5_0
  - webencodings=0.5.1=py311hca03da5_1
  - websocket-client=1.8.0=py311hca03da5_0
  - wheel=0.45.1=py311hca03da5_0
  - widgetsnbextension=4.0.13=py311hca03da5_0
  - wrapt=1.17.0=py311h80987f9_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h2c7f8f0_1
  - zlib=1.3.1=h5f15de7_0
  - zstd=1.5.7=h817c040_0
  - pip:
      - absl-py==2.3.1
      - adagio==0.2.6
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - astunparse==1.6.3
      - brotli==1.1.0
      - cachetools==6.2.1
      - cloudpickle==3.1.2
      - coreforecast==0.0.16
      - dataclasses-json==0.6.7
      - ddgs==9.6.1
      - faiss-cpu==1.12.0
      - filetype==1.2.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - fugue==0.9.2
      - gast==0.6.0
      - geopandas==1.1.1
      - google-ai-generativelanguage==0.9.0
      - google-api-core==2.27.0
      - google-api-python-client==2.185.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.0
      - google-pasta==0.2.0
      - googleapis-common-protos==1.71.0
      - grpcio==1.76.0
      - grpcio-status==1.76.0
      - h2==4.3.0
      - h5py==3.15.1
      - hpack==4.1.0
      - httplib2==0.31.0
      - httpx-sse==0.4.3
      - hyperframe==6.1.0
      - imbalanced-learn==0.14.0
      - imblearn==0.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - keras==3.12.0
      - langchain==1.0.2
      - langchain-classic==1.0.0
      - langchain-community==0.4
      - langchain-core==1.0.1
      - langchain-google-genai==3.0.0
      - langchain-text-splitters==1.0.0
      - langgraph==1.0.1
      - langgraph-checkpoint==3.0.0
      - langgraph-prebuilt==1.0.1
      - langgraph-sdk==0.2.9
      - langsmith==0.4.38
      - libclang==18.1.1
      - llvmlite==0.45.1
      - lxml==6.0.2
      - markdown==3.10
      - marshmallow==3.26.1
      - ml-dtypes==0.5.4
      - multidict==6.7.0
      - mypy-extensions==1.1.0
      - namex==0.1.0
      - narwhals==2.12.0
      - networkx==3.5
      - nixtla==0.7.1
      - numba==0.62.1
      - opt-einsum==3.4.0
      - optree==0.18.0
      - orjson==3.11.4
      - ormsgpack==1.11.0
      - osmnx==2.0.6
      - plotly==6.5.0
      - primp==0.15.0
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.0
      - ptitprince==0.3.1
      - pulp==3.3.0
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic-settings==2.11.0
      - pymupdf==1.26.5
      - pyobjc==12.0
      - pyobjc-core==12.0
      - pyobjc-framework-accessibility==12.0
      - pyobjc-framework-accounts==12.0
      - pyobjc-framework-addressbook==12.0
      - pyobjc-framework-adservices==12.0
      - pyobjc-framework-adsupport==12.0
      - pyobjc-framework-applescriptkit==12.0
      - pyobjc-framework-applescriptobjc==12.0
      - pyobjc-framework-applicationservices==12.0
      - pyobjc-framework-apptrackingtransparency==12.0
      - pyobjc-framework-arkit==12.0
      - pyobjc-framework-audiovideobridging==12.0
      - pyobjc-framework-authenticationservices==12.0
      - pyobjc-framework-automaticassessmentconfiguration==12.0
      - pyobjc-framework-automator==12.0
      - pyobjc-framework-avfoundation==12.0
      - pyobjc-framework-avkit==12.0
      - pyobjc-framework-avrouting==12.0
      - pyobjc-framework-backgroundassets==12.0
      - pyobjc-framework-browserenginekit==12.0
      - pyobjc-framework-businesschat==12.0
      - pyobjc-framework-calendarstore==12.0
      - pyobjc-framework-callkit==12.0
      - pyobjc-framework-carbon==12.0
      - pyobjc-framework-cfnetwork==12.0
      - pyobjc-framework-cinematic==12.0
      - pyobjc-framework-classkit==12.0
      - pyobjc-framework-cloudkit==12.0
      - pyobjc-framework-cocoa==12.0
      - pyobjc-framework-collaboration==12.0
      - pyobjc-framework-colorsync==12.0
      - pyobjc-framework-compositorservices==12.0
      - pyobjc-framework-contacts==12.0
      - pyobjc-framework-contactsui==12.0
      - pyobjc-framework-coreaudio==12.0
      - pyobjc-framework-coreaudiokit==12.0
      - pyobjc-framework-corebluetooth==12.0
      - pyobjc-framework-coredata==12.0
      - pyobjc-framework-corehaptics==12.0
      - pyobjc-framework-corelocation==12.0
      - pyobjc-framework-coremedia==12.0
      - pyobjc-framework-coremediaio==12.0
      - pyobjc-framework-coremidi==12.0
      - pyobjc-framework-coreml==12.0
      - pyobjc-framework-coremotion==12.0
      - pyobjc-framework-coreservices==12.0
      - pyobjc-framework-corespotlight==12.0
      - pyobjc-framework-coretext==12.0
      - pyobjc-framework-corewlan==12.0
      - pyobjc-framework-cryptotokenkit==12.0
      - pyobjc-framework-datadetection==12.0
      - pyobjc-framework-devicecheck==12.0
      - pyobjc-framework-devicediscoveryextension==12.0
      - pyobjc-framework-dictionaryservices==12.0
      - pyobjc-framework-discrecording==12.0
      - pyobjc-framework-discrecordingui==12.0
      - pyobjc-framework-diskarbitration==12.0
      - pyobjc-framework-dvdplayback==12.0
      - pyobjc-framework-eventkit==12.0
      - pyobjc-framework-exceptionhandling==12.0
      - pyobjc-framework-executionpolicy==12.0
      - pyobjc-framework-extensionkit==12.0
      - pyobjc-framework-externalaccessory==12.0
      - pyobjc-framework-fileprovider==12.0
      - pyobjc-framework-fileproviderui==12.0
      - pyobjc-framework-findersync==12.0
      - pyobjc-framework-fsevents==12.0
      - pyobjc-framework-fskit==12.0
      - pyobjc-framework-gamecenter==12.0
      - pyobjc-framework-gamecontroller==12.0
      - pyobjc-framework-gamekit==12.0
      - pyobjc-framework-gameplaykit==12.0
      - pyobjc-framework-gamesave==12.0
      - pyobjc-framework-healthkit==12.0
      - pyobjc-framework-imagecapturecore==12.0
      - pyobjc-framework-inputmethodkit==12.0
      - pyobjc-framework-installerplugins==12.0
      - pyobjc-framework-instantmessage==12.0
      - pyobjc-framework-intents==12.0
      - pyobjc-framework-intentsui==12.0
      - pyobjc-framework-iobluetooth==12.0
      - pyobjc-framework-iobluetoothui==12.0
      - pyobjc-framework-iosurface==12.0
      - pyobjc-framework-ituneslibrary==12.0
      - pyobjc-framework-kernelmanagement==12.0
      - pyobjc-framework-latentsemanticmapping==12.0
      - pyobjc-framework-launchservices==12.0
      - pyobjc-framework-libdispatch==12.0
      - pyobjc-framework-libxpc==12.0
      - pyobjc-framework-linkpresentation==12.0
      - pyobjc-framework-localauthentication==12.0
      - pyobjc-framework-localauthenticationembeddedui==12.0
      - pyobjc-framework-mailkit==12.0
      - pyobjc-framework-mapkit==12.0
      - pyobjc-framework-mediaaccessibility==12.0
      - pyobjc-framework-mediaextension==12.0
      - pyobjc-framework-medialibrary==12.0
      - pyobjc-framework-mediaplayer==12.0
      - pyobjc-framework-mediatoolbox==12.0
      - pyobjc-framework-metal==12.0
      - pyobjc-framework-metalfx==12.0
      - pyobjc-framework-metalkit==12.0
      - pyobjc-framework-metalperformanceshaders==12.0
      - pyobjc-framework-metalperformanceshadersgraph==12.0
      - pyobjc-framework-metrickit==12.0
      - pyobjc-framework-mlcompute==12.0
      - pyobjc-framework-modelio==12.0
      - pyobjc-framework-multipeerconnectivity==12.0
      - pyobjc-framework-naturallanguage==12.0
      - pyobjc-framework-netfs==12.0
      - pyobjc-framework-network==12.0
      - pyobjc-framework-networkextension==12.0
      - pyobjc-framework-notificationcenter==12.0
      - pyobjc-framework-opendirectory==12.0
      - pyobjc-framework-osakit==12.0
      - pyobjc-framework-oslog==12.0
      - pyobjc-framework-passkit==12.0
      - pyobjc-framework-pencilkit==12.0
      - pyobjc-framework-phase==12.0
      - pyobjc-framework-photos==12.0
      - pyobjc-framework-photosui==12.0
      - pyobjc-framework-preferencepanes==12.0
      - pyobjc-framework-pushkit==12.0
      - pyobjc-framework-quartz==12.0
      - pyobjc-framework-quicklookthumbnailing==12.0
      - pyobjc-framework-replaykit==12.0
      - pyobjc-framework-safariservices==12.0
      - pyobjc-framework-safetykit==12.0
      - pyobjc-framework-scenekit==12.0
      - pyobjc-framework-screencapturekit==12.0
      - pyobjc-framework-screensaver==12.0
      - pyobjc-framework-screentime==12.0
      - pyobjc-framework-scriptingbridge==12.0
      - pyobjc-framework-searchkit==12.0
      - pyobjc-framework-security==12.0
      - pyobjc-framework-securityfoundation==12.0
      - pyobjc-framework-securityinterface==12.0
      - pyobjc-framework-securityui==12.0
      - pyobjc-framework-sensitivecontentanalysis==12.0
      - pyobjc-framework-servicemanagement==12.0
      - pyobjc-framework-sharedwithyou==12.0
      - pyobjc-framework-sharedwithyoucore==12.0
      - pyobjc-framework-shazamkit==12.0
      - pyobjc-framework-social==12.0
      - pyobjc-framework-soundanalysis==12.0
      - pyobjc-framework-speech==12.0
      - pyobjc-framework-spritekit==12.0
      - pyobjc-framework-storekit==12.0
      - pyobjc-framework-symbols==12.0
      - pyobjc-framework-syncservices==12.0
      - pyobjc-framework-systemconfiguration==12.0
      - pyobjc-framework-systemextensions==12.0
      - pyobjc-framework-threadnetwork==12.0
      - pyobjc-framework-uniformtypeidentifiers==12.0
      - pyobjc-framework-usernotifications==12.0
      - pyobjc-framework-usernotificationsui==12.0
      - pyobjc-framework-videosubscriberaccount==12.0
      - pyobjc-framework-videotoolbox==12.0
      - pyobjc-framework-virtualization==12.0
      - pyobjc-framework-vision==12.0
      - pyobjc-framework-webkit==12.0
      - pyogrio==0.11.1
      - pyproj==3.7.2
      - python-dotenv==1.1.1
      - pyttsx3==2.99
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - scipy==1.15.3
      - shap==0.50.0
      - shapely==2.1.2
      - slicer==0.0.8
      - socksio==1.0.0
      - sqlalchemy==2.0.44
      - statsforecast==2.0.3
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - triad==1.0.0
      - typing-inspect==0.9.0
      - uritemplate==4.2.0
      - utilsforecast==0.2.14
      - werkzeug==3.1.3
      - wikipedia==1.4.0
      - xgboost==3.1.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zstandard==0.25.0
prefix: /opt/anaconda3/envs/AAI
